title: kapil chaudhary
email: mail@eduardoboucas.com
description: "Software engineer with a crush on the web"
baseurl: ""
url: "https://eduardoboucas.com"

markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - node_modules
  - vendor

paginate: 9
paginate_path: "/page/:num/"

# googleAnalyticsId:   

gems:
  - jekyll-paginate
  - jekyll-github-metadata
  - jemoji

excerpt_separator: <!--more-->

collections:
  tv:
    output: true

defaults:
  - scope:
      path: ""
      type: tv
    values:
      layout: tv
      permalink: /video/:title

future: true

# Serving
detach:  false
port:    4100
host:    0.0.0.0

# Staticman
# staticmanUrl: 
